import type { WorkflowDefinition } from '@astan/contracts';

/**
 * Workflow «مشاهده ابلاغیه» (سند §9، §34).
 *
 * The step graph mirrors the real journey on the judicial e-services portal:
 * درگاه → سامانه ثنا (ورود) → رمز موقت → صفحه ابلاغ → فهرست ابلاغیه‌ها →
 * اطلاعات ابلاغیه → دریافت/چاپ.
 *
 * Every transition is driven by a host-emitted event. There is no timer, no
 * DOM polling and no model-inferred progress.
 */
export const VIEW_NOTIFICATION: WorkflowDefinition = {
  workflow_id: 'VIEW_NOTIFICATION',
  title: 'مشاهده ابلاغیه',
  description: 'راهنمای گام‌به‌گام برای ورود به سامانه و مشاهده یا دریافت ابلاغیه.',
  initial_step: 'START',
  visible_steps: ['LOGIN', 'OTP_VERIFICATION', 'NOTIFICATION_LIST', 'NOTIFICATION_DETAIL', 'DOWNLOAD_OR_VIEW'],
  steps: {
    START: {
      step_id: 'START',
      title: 'شروع فرآیند',
      description: 'برای مشاهده ابلاغیه، ابتدا باید وارد سامانه ابلاغ الکترونیک قضایی شوید.',
      simple_description: 'اول باید وارد سامانه شوید. من مسیر را نشانتان می‌دهم.',
      expected_pages: ['PAGE_HOME', 'PAGE_UNKNOWN'],
      allowed_targets: ['notification_service_card', 'login_modal_primary_button', 'services_grid'],
      primary_target: 'notification_service_card',
      transitions: {
        LOGIN_PAGE_OPENED: 'LOGIN',
        PAGE_VIEWED: 'START',
        LOGIN_SUCCESS: 'OTP_VERIFICATION',
      },
      error_events: ['SERVICE_UNAVAILABLE', 'NETWORK_ERROR'],
      order: 0,
      terminal: false,
    },
    LOGIN: {
      step_id: 'LOGIN',
      title: 'ورود به سامانه ثنا',
      description: 'در سامانه احراز هویت ثنا، نوع شخص را انتخاب کنید و شماره ملی و رمز شخصی خود را وارد کنید، سپس «مرحله بعد» را بزنید.',
      simple_description: 'در فرم روبه‌رو شماره ملی و رمز شخصی‌تان را بنویسید و دکمه آبی «مرحله بعد» را بزنید. من فرم را برایتان مشخص کرده‌ام.',
      expected_pages: ['PAGE_LOGIN'],
      allowed_targets: ['login_form', 'login_person_type_tabs', 'login_national_id', 'login_password', 'login_submit', 'login_forgot_password'],
      primary_target: 'login_form',
      transitions: {
        LOGIN_SUCCESS: 'OTP_VERIFICATION',
        OTP_SENT: 'OTP_VERIFICATION',
        LOGIN_FAILED: 'LOGIN',
        LOGIN_SUBMITTED: 'LOGIN',
        PAGE_VIEWED: 'LOGIN',
      },
      error_events: ['LOGIN_FAILED', 'INVALID_CREDENTIALS', 'ACCOUNT_LOCKED', 'SERVICE_UNAVAILABLE', 'NETWORK_ERROR'],
      order: 1,
      terminal: false,
    },
    OTP_VERIFICATION: {
      step_id: 'OTP_VERIFICATION',
      title: 'تأیید رمز موقت',
      description: 'رمز موقتی که به تلفن همراه ثبت‌شده در ثنا پیامک شده است را در کادر وارد کنید و «ورود به سامانه» را بزنید.',
      simple_description: 'یک پیامک با یک کد برایتان می‌آید. همان کد را در کادر بنویسید و دکمه ورود را بزنید.',
      expected_pages: ['PAGE_OTP'],
      allowed_targets: ['otp_form', 'otp_input', 'otp_submit', 'otp_resend', 'otp_back'],
      primary_target: 'otp_input',
      transitions: {
        OTP_VERIFIED: 'AUTHENTICATED',
        DASHBOARD_LOADED: 'AUTHENTICATED',
        OTP_FAILED: 'OTP_VERIFICATION',
        OTP_SENT: 'OTP_VERIFICATION',
        OTP_SUBMITTED: 'OTP_VERIFICATION',
        OTP_RESEND_REQUESTED: 'OTP_VERIFICATION',
        PAGE_VIEWED: 'OTP_VERIFICATION',
      },
      error_events: ['OTP_NOT_RECEIVED', 'INVALID_OTP', 'OTP_EXPIRED', 'SESSION_EXPIRED', 'SERVICE_UNAVAILABLE', 'NETWORK_ERROR'],
      order: 2,
      terminal: false,
    },
    AUTHENTICATED: {
      step_id: 'AUTHENTICATED',
      title: 'ورود به بخش ابلاغیه‌ها',
      description: 'وارد سامانه شدید. برای دیدن ابلاغیه‌های تازه، کاشی «ابلاغیه جدید» را انتخاب کنید.',
      simple_description: 'وارد شدید. حالا روی کادری که نوشته «ابلاغیه جدید» کلیک کنید.',
      expected_pages: ['PAGE_DASHBOARD'],
      allowed_targets: ['dashboard_tiles', 'tile_new_notification', 'tile_viewed_notifications', 'tile_notification_by_code', 'tile_notification_by_number', 'tile_my_services'],
      primary_target: 'tile_new_notification',
      transitions: {
        NOTIFICATION_LIST_LOADED: 'NOTIFICATION_LIST',
        NOTIFICATION_EMPTY: 'NOTIFICATION_LIST',
        DASHBOARD_LOADED: 'AUTHENTICATED',
        PAGE_VIEWED: 'AUTHENTICATED',
        SESSION_EXPIRED_EVENT: 'LOGIN',
        USER_LOGGED_OUT: 'LOGIN',
      },
      error_events: ['SESSION_EXPIRED', 'SERVICE_UNAVAILABLE', 'NETWORK_ERROR'],
      order: 3,
      terminal: false,
    },
    NOTIFICATION_LIST: {
      step_id: 'NOTIFICATION_LIST',
      title: 'فهرست ابلاغیه‌ها',
      description: 'یکی از ابلاغیه‌های فهرست را انتخاب کنید تا جزئیات آن باز شود.',
      simple_description: 'در فهرست روبه‌رو روی سطر ابلاغیه‌ای که می‌خواهید ببینید کلیک کنید.',
      expected_pages: ['PAGE_NOTIFICATION_LIST'],
      allowed_targets: ['notification_list', 'notification_list_first_row', 'notification_list_refresh'],
      primary_target: 'notification_list_first_row',
      transitions: {
        NOTIFICATION_OPENED: 'NOTIFICATION_DETAIL',
        NOTIFICATION_LIST_LOADED: 'NOTIFICATION_LIST',
        NOTIFICATION_EMPTY: 'NOTIFICATION_LIST',
        PAGE_VIEWED: 'NOTIFICATION_LIST',
        SESSION_EXPIRED_EVENT: 'LOGIN',
      },
      error_events: ['NOTIFICATION_NOT_FOUND', 'SESSION_EXPIRED', 'SERVICE_UNAVAILABLE', 'NETWORK_ERROR'],
      order: 4,
      terminal: false,
    },
    NOTIFICATION_DETAIL: {
      step_id: 'NOTIFICATION_DETAIL',
      title: 'مشاهده ابلاغیه',
      description: 'متن ابلاغیه در این صفحه نمایش داده می‌شود. برای دریافت نسخه چاپی یا فایل پیوست از دکمه‌های پایین صفحه استفاده کنید.',
      simple_description: 'متن ابلاغیه همین‌جاست. اگر نسخه‌ای برای خودتان می‌خواهید، دکمه «نسخه چاپی ابلاغیه» را بزنید.',
      expected_pages: ['PAGE_NOTIFICATION_DETAIL'],
      allowed_targets: ['notification_body', 'notification_print_button', 'notification_preview_button', 'notification_attachment_button', 'notification_more_options', 'notification_download_button'],
      primary_target: 'notification_body',
      transitions: {
        DOWNLOAD_STARTED: 'DOWNLOAD_OR_VIEW',
        PRINT_OPENED: 'DOWNLOAD_OR_VIEW',
        NOTIFICATION_OPENED: 'NOTIFICATION_DETAIL',
        PAGE_VIEWED: 'NOTIFICATION_DETAIL',
        SESSION_EXPIRED_EVENT: 'LOGIN',
      },
      error_events: ['NOTIFICATION_NOT_FOUND', 'SESSION_EXPIRED', 'SERVICE_UNAVAILABLE', 'NETWORK_ERROR'],
      order: 5,
      terminal: false,
    },
    DOWNLOAD_OR_VIEW: {
      step_id: 'DOWNLOAD_OR_VIEW',
      title: 'دریافت یا چاپ ابلاغیه',
      description: 'نسخه چاپی باز شد. می‌توانید آن را چاپ کنید یا به‌صورت فایل ذخیره کنید.',
      simple_description: 'صفحه چاپ باز شده است. دکمه «چاپ اطلاعات» را بزنید تا چاپ یا ذخیره شود.',
      expected_pages: ['PAGE_NOTIFICATION_PRINT', 'PAGE_NOTIFICATION_DETAIL'],
      allowed_targets: ['notification_print_button', 'notification_download_button', 'notification_body'],
      primary_target: 'notification_print_button',
      transitions: {
        DOWNLOAD_COMPLETED: 'COMPLETED',
        PRINT_OPENED: 'DOWNLOAD_OR_VIEW',
        DOWNLOAD_STARTED: 'DOWNLOAD_OR_VIEW',
        PAGE_VIEWED: 'DOWNLOAD_OR_VIEW',
      },
      error_events: ['DOWNLOAD_FAILED', 'SERVICE_UNAVAILABLE', 'NETWORK_ERROR'],
      order: 6,
      terminal: false,
    },
    COMPLETED: {
      step_id: 'COMPLETED',
      title: 'پایان فرآیند',
      description: 'ابلاغیه شما دریافت شد. اگر کار دیگری دارید در خدمتم.',
      simple_description: 'تمام شد. ابلاغیه‌تان را گرفتید.',
      expected_pages: ['PAGE_NOTIFICATION_PRINT', 'PAGE_NOTIFICATION_DETAIL', 'PAGE_DASHBOARD'],
      allowed_targets: [],
      primary_target: null,
      transitions: { PAGE_VIEWED: 'COMPLETED' },
      error_events: [],
      order: 7,
      terminal: true,
    },
  },
};
